theme: jekyll-theme-conference
ignore_theme_config: true

title: 'Proof Society 2025'
description: >-
  7<sup>th</sup> International School and Workshop on Proof Theory<br>
  <small>September 1–5, Ghent, Belgium</small>

url: https://proof2025.ugent.be

# collections:
#   talks:
#     output: true
#     permalink: /talks/:title/
#   speakers:
#     output: true
#   rooms:
#     output: true

# defaults:
#   - scope:
#       path: ''
#       type: talks
#     values:
#       layout: talk
#   - scope:
#       path: ''
#       type: speakers
#     values:
#       layout: speaker
#   - scope:
#       path: ''
#       type: rooms
#     values:
#       layout: room

conference:
  lang: en
  tz: "+02:00"
  show_errors: false
  info_bars:
    - title: Spam emails
      color: warning
      text: |
        **IMPORTANT**: Please ignore any spam emails coming from suspicious addresses (like ``coordination@travelhostingservices.com``) targeting speakers and participants of the event; do not reply to them, or click on any links. Make sure to communicate only with addresses ending in ``@ugent.be`` and known organizers.
  navigation:
    logo:
      name: '<sup class="logo-ugent">UGent</sup><span class="logo-logic">Logic</span>'
      url: 'https://logicseminar.ugent.be'
    breakpoint: md
    links:
      - name: Program
        disabled: true
        # menu:
        #   - name: Program Overview
        #     relative_url: /program/
        #   - name: Talks Overview
        #     relative_url: /talks/
        #   - name: Speakers Overview
        #     relative_url: /speakers/
      - name: Information
        disabled: false
        menu:
          - name: Location
            relative_url: /information/location
        #   - name: Practical
        #     relative_url: /information/practical
      - name: Registration
        relative_url: /registration
      - name: 'Previous Editions'
        menu:
          - name: Utrecht, The Netherlands, 2022
            absolute_url: 'https://uswpt.sites.uu.nl/'
          - name: Barcelona, Spain, 2023 (Workshop)
            absolute_url: 'https://www.ub.edu/prooftheory/event/tps2023workshop/'
          - name: Barcelona, Spain, 2023 (School)
            absolute_url: 'https://www.ub.edu/prooftheory/event/tps2023school/'
          - name: Birmingham, UK, 2024
            absolute_url: 'https://proofsociety2024.com/'
          - name: (All Editions)
            absolute_url: 'https://www.proofsociety.org/category/past-events/'

  location:
    hide: true
    url: /location
    navbar_title: Location
    map:
      home_coord: 51.05337318958073, 3.727216194283345
      map_provider: 'CartoDB.Voyager'
      default_zoom: 18

  program:
    url: /program
    time_steps: 15
    show_alltimes: true

  talks:
    main_categories:
      - name: Tutorials
        color: warning
      - name: Invited Talks
        color: primary
      - name: Contributed Talks
        color: info
      - name: Events
        color: success
        hide: true
      - name: Breaks
        color: light
        hide: true
      - name: Special
        color: dark
        hide: true

  speakers:
    show_firstname: true
    show_university: true

include:
  - .htaccess
  - .default.html

exclude:
  - README.md

kramdown:
  math_engine: katex

incremental: false
